### ISSUE TITLE
ios: search screen overlaps bottom bar when transitioning from favorites

### ISSUE THREAD

**Issue by technicat** [technicat/talkdimsum#25]

**Comment by technicat** [comment]
I think this happens after performing a search

**Comment by spellitwithaph** [comment]
STR: 
* click search (foot nav)
* select any existing result (eg 7up)
* click back (top left)
* footer nav appears transparent on top of results

**Comment by technicat** [comment]
Thanks for the reproducible case!

I've narrowed down the SwiftUI behavior, the bug doesn't happen if I remove the search bar, so it happens with a VStack containing a View and a List but not just a List by itself a or VStack contaning just a List.

Verified this with the countries display on the far right tab, which is just a List but adding a Text field before it in a VStack exhibits the same behavior.
